### ISSUE TITLE
There is a mistake in Exercise 1.44.

### ISSUE THREAD

**Issue by Miloas** [gregsexton/SICP-Clojure#1]
Hi,I found you miss the "3" in function "smooth".

Your code:

``` clojure
(defn smooth [f]
  (fn [x]
    (/ (+ (f (- x dx))
          (f x)
          (f (+ x dx))))))
```

The right code:

``` clojure
(defn smooth [f]
  (fn [x]
    (/ (+ (f (- x dx))
          (f x)
          (f (+ x dx)))
       3)))
```

I'm learning Clojure ,thanks for your Clojure solutions . :)

And Sorry for my poor English.

**Comment by gregsexton** [comment]
Thanks a lot for pointing this out!
